### ISSUE TITLE
The version of the parent pom should be updated to the latest available

### ISSUE THREAD

**Issue by martin-g** [testcontainers/testcontainers-java-module-mssqlserver#1]
At the moment this module uses `1.2.1` of testcontainers-parent.
Latest release is `1.3.1`.
I'd send a Pull Request but I am not sure what is the purpose of the special value `0-SNAPSHOT`.

**Comment by rnorth** [comment]
We're on the right parent version as of about a month ago, so I'll resolve this. FWIW I intend to bump the parent version whenever necessary to follow a parent project change, but hope to make this more efficient in the near future.
