### ISSUE TITLE
Publishing to Maven Central appears to be broken

### ISSUE THREAD

**Issue by vpavic** [testcontainers/testcontainers-java-module-mssqlserver#10]
Both [changelog](https://github.com/testcontainers/testcontainers-java-module-mssqlserver/blob/master/CHANGELOG.md) and [releases page](https://github.com/testcontainers/testcontainers-java-module-mssqlserver/releases) refer to `1.5.0` and `1.5.1` releases, however the Maven Central has `1.4.3` as the [only available release](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.testcontainers%22%20AND%20a%3A%22mssqlserver%22).

Related to testcontainers/testcontainers-java-module-mariadb#6 and #3.

**Comment by rnorth** [comment]
Sorry, yes, something isn't right. I've retriggered the CI release process and things look all good right now - awaiting actual arrival on maven central. However, the logs showed everything OK on the 19th Dec as well, so I'll watch closely.

Sorry for taking so long to respond.

**Comment by vpavic** [comment]
Thanks for the feedback @rnorth. Yes, I can see the `org.testcontainers:mssqlserver:1.5.1` artifact in the Maven Central now.

However, the MariaDB artifact (see the issue link in the opening comment) is still at `1.4.3`.

**Comment by vpavic** [comment]
Closing as `1.5.1` is available in the Maven Central as of January 17th.
