### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by axelfontaine** [testcontainers/testcontainers-java-module-mssqlserver#3]
Like all other TC modules

**Comment by lhotari** [comment]
In the meantime you can use Jitpack: https://jitpack.io/#testcontainers/testcontainers-java-module-mssqlserver

**Comment by lhotari** [comment]
@rnorth [This commit](https://github.com/testcontainers/testcontainers-java-module-mssqlserver/commit/0ac2f8d0553b5c4e2c30e7e5e84514f6a03464af#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR6) mentions that 1.4.3 was pushed to maven central. However, it's still missing. Did this module (mssqlserver) get released?

**Comment by rnorth** [comment]
Damn, I'll have a look and see if I can find out why this artifact wasn't published. Sorry.

**Comment by lhotari** [comment]
@rnorth I wonder if missing `scm` or `url` element was the reason why publishing to Maven central failed? I made PR #8 to fix that.

**Comment by rnorth** [comment]
#8 solved the problem; artefacts are now published.
